name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Install Playwright browsers with system deps
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # ✅ Install Allure CLI
      - name: Install Allure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip default-jre wget
          wget https://github.com/allure-framework/allure2/releases/download/2.30.0/allure-2.30.0.zip
          unzip allure-2.30.0.zip -d /opt/
          sudo ln -s /opt/allure-2.30.0/bin/allure /usr/bin/allure
          allure --version

      # Debug: list test files
      - name: Debug – list test files
        run: ls -R e2e/tests

      # Run Playwright tests (uses config: testDir = e2e/tests)
      - name: Run Playwright tests
        run: npx playwright test logintest.spec.js --project=chromium --reporter=html,allure-playwright

      # Generate Allure Report
      - name: Generate Allure Report
        run: allure generate allure-results --clean -o allure-report

      # Upload Allure Report
      - name: Upload Allure Report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/
          retention-days: 30

      # Upload Playwright HTML Report
      - name: Upload Playwright HTML Report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
